apiVersion: v1
kind: Service
metadata:
  name: hello-service #service名
spec:
  type: NodePort
  selector:
    app: nginx # 公開したいpodのラベル（pod用のmanifestで設定したlabelのKeyとValueが一致するもの）
  ports:
    - port: 80 #内部で使うポート
      nodePort: 30001 #クラスタ外からアクセスするときに使うポート
      protocol: TCP
